// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UaZ15s6nS2A6oxv_HZR39ywqu9hl8uo',
    appId: '1:141926608644:web:19dd753c7403257ed7ea51',
    messagingSenderId: '141926608644',
    projectId: 'crud-48b94',
    authDomain: 'crud-48b94.firebaseapp.com',
    storageBucket: 'crud-48b94.appspot.com',
    measurementId: 'G-T0HRVFY12G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnoKlUuEZUAZMaVW6jNQ8ZsvRkscvMtc',
    appId: '1:141926608644:android:042a4bb2ac7873a9d7ea51',
    messagingSenderId: '141926608644',
    projectId: 'crud-48b94',
    storageBucket: 'crud-48b94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtgjUbv5RIamNZFwUCUo8MA3fF1a8tyI',
    appId: '1:141926608644:ios:bb40c776102c843bd7ea51',
    messagingSenderId: '141926608644',
    projectId: 'crud-48b94',
    storageBucket: 'crud-48b94.appspot.com',
    iosBundleId: 'com.example.firstapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtgjUbv5RIamNZFwUCUo8MA3fF1a8tyI',
    appId: '1:141926608644:ios:80d0b2397196cc8cd7ea51',
    messagingSenderId: '141926608644',
    projectId: 'crud-48b94',
    storageBucket: 'crud-48b94.appspot.com',
    iosBundleId: 'com.example.firstapp.RunnerTests',
  );
}
