// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVpIPaegnOs_aVeqT6GH9PeeeWdCwhcI',
    appId: '1:26185832194:web:5f9a92506657737d64141b',
    messagingSenderId: '26185832194',
    projectId: 'autenticate-5ee91',
    authDomain: 'autenticate-5ee91.firebaseapp.com',
    storageBucket: 'autenticate-5ee91.appspot.com',
    measurementId: 'G-N2FT4545CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSHNkseQPe4PabyaySoHNuVK5WnOulXjw',
    appId: '1:26185832194:android:432f76e505ef81c464141b',
    messagingSenderId: '26185832194',
    projectId: 'autenticate-5ee91',
    storageBucket: 'autenticate-5ee91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPodNPblD03w2MmeQK6D9J2cKZdN625M',
    appId: '1:26185832194:ios:25b0456f627f02b764141b',
    messagingSenderId: '26185832194',
    projectId: 'autenticate-5ee91',
    storageBucket: 'autenticate-5ee91.appspot.com',
    iosBundleId: 'com.example.autenticacao2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIPodNPblD03w2MmeQK6D9J2cKZdN625M',
    appId: '1:26185832194:ios:e1fc195db22a3cd564141b',
    messagingSenderId: '26185832194',
    projectId: 'autenticate-5ee91',
    storageBucket: 'autenticate-5ee91.appspot.com',
    iosBundleId: 'com.example.autenticacao2.RunnerTests',
  );
}
